name: Deploy Astro site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          cd astrosite
          npm install
      - name: Build
        run: |
          cd astrosite
          npm run build
      - name: Copy CNAME
        run: cp CNAME dist/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./astrosite/dist

permissions:
  contents: write